### ISSUE TITLE
Position interpolation based on line geometry plus a distance

### ISSUE THREAD

**Issue by sim51** [OpenRailAssociation/osrd#2611] opened 2022-12-15 14:54 UTC
In the editor UI, we need to compute the position of a signal based on a line/distance, so when a user change the position of an item, it directly see the modification on the map.

The backend is doing the same thing, but the code is not exactly the same.

The behavior should be the same, front & back

**Comment by flomonster** [comment] 2023-03-02 08:53
Duplicate of 1751

**Closed as completed by flomonster** 2023-03-02 08:53 UTC
Labels: kind:bug, area:front, severity:minor, area:editoast
