### ISSUE TITLE
front: linear data layers prevent placing points on tracks

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#2927] opened 2023-01-18 08:52 UTC
### What happened?

When displaying some linear data (catenary voltages, speed limits) on the map, one can't place path points (start, stop and waypoints). 

It seems that the point can't snap to tracks when there are linear data layers over it.

Then if I want to build a path depending on some linear data, I have to switch the layer on and off indefinitely. 

### What did you expect to happen?

I'd like to be able to see linear data layers AND build paths at the same time

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to /osrd/settings/
2. Display catenary voltages on the maps
3. Try to place a point on the map

### What operating system and browser are you using? (if applicable)

- Ubuntu
- FireFox

### OSRD version

1.0

**Comment by anisometropie** [comment] 2023-02-10 18:06
demo video : https://github.com/DGEXSolutions/osrd/issues/3162

**Comment by leovalais** [comment] 2023-02-16 13:43
Possible duplicate of #3150 ?

**Comment by ttsirkia** [comment] 2023-02-18 08:55
This can be fixed (unless it causes some problems I didn't notice) by limiting the layers to be queried.

For example, here:
https://github.com/DGEXSolutions/osrd/blob/dev/front/src/applications/operationalStudies/components/ManageTrainSchedule/Map.tsx#L105
`const result = getMapMouseEventNearestFeature(e, {layersId: ['chartis/tracks-sch/main']});`

And similarly in `onFeatureClick`.

However, MapLibre will fail if querying from a layer which does not exists, so there needs to be an additioanl check if the map is in geometry or schematic mode and place the correct layer name.

**Closed as completed** 2023-02-20 17:07 UTC
Labels: kind:bug, area:front, severity:minor
