### ISSUE TITLE
stdcm: Selecting suggestion doesn't filled up correctly input field

### ISSUE THREAD

**Issue by woshilapin** [OpenRailAssociation/osrd#9308] opened 2024-10-11 09:41 UTC
> [!NOTE]
> Trigrams will be displayed differently, the UI is being designed. It should prevent this misunderstanding.

### What happened?

When I type a text searching for a intermediate Operational Point, I get some suggestions. In this case, typing "Le Pon" propose a suggestion "LPT Le Pontet". If I select it (with mouse or with keyboard), the input field is filled up with "Le Pontet", not what I selected which is "LPT Le Pontet". If I click again on the `∨` on the right of the input field, and click again on the suggestion (or even if I click on the side to close the suggestions' popup), the input field is not filled up with "LPT Le Pontet".

### What did you expect to happen?

I expect the field to be filled up with what is shown and selected in the suggestion popup.

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/user-attachments/assets/3b21f440-5440-40ce-8674-4eb18acf7c3f

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

96c960e (editoast, core) but nothing shown for front

**Comment by woshilapin** [comment] 2024-10-11 12:31
Might be related to https://github.com/OpenRailAssociation/osrd/issues/9296 🤷

**Comment by axrolld** [comment] 2024-10-15 17:11
IMO (agreed with @thibautsailly ) the trigram should not be displayed once the field is selected. It's here in the suggestions because it can be an input but it should remain after the selection. We could maybe make this clearer i think. But in that case the bug is actually the second part : clicking in then out of the combo box make the trigram visible.
I'm postponing this until we set this clear.

**Comment by axrolld** [comment] 2024-10-29 09:26
Expected behavior gathered in [this bug](https://github.com/OpenRailAssociation/osrd/issues/9356). I'm closing this one if that's ok for you @woshilapin .

**Closed as completed by axrolld** 2024-10-29 09:26 UTC
Labels: kind:bug, area:front, severity:minor, module:stdcm, postponed
