### ISSUE TITLE
Train paths can't go over the same position more than once

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#216] opened 2021-10-08 13:08 UTC
To support this we need to remove this method and all of its uses: https://github.com/DGEXSolutions/osrd-core/blob/dev/src/main/java/fr/sncf/osrd/train/TrainPath.java#L131-L145

We would probably need to change many things in the API, since interactions are given in track locations.

**Comment by flomonster** [comment] 2023-07-20 07:39
Duplicate of #187

**Closed as completed by flomonster** 2023-07-20 07:39 UTC
Labels: area:core
