### ISSUE TITLE
front: space-time-chart: train names don't match the actual trains

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#8537] opened 2024-08-22 11:41 UTC
### What happened?

See video, pay attention to the train names at the top of the space time chart (scheduled / projection):

[Screencast from 22-08-2024 13:37:15.webm](https://github.com/user-attachments/assets/1018469d-6e1b-4b0b-8c19-b8c611fef396)

"projection" is supposed to be the short one and "scheduled" the longer one. They don't overlap at all. I'm switching from one path to the other, we should only see the train for the given path. 

### What did you expect to happen?

The names should match.

### How can we reproduce it (as minimally and precisely as possible)?

1. Schedule two trains with different names, it's easier if they don't overlap at all
2. Click around the "use this path" button
3. Also click on the train themselves (left of the "use this path")

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

77ed9b9e027aaad67ad2b9a049675f53226e9be8

**Comment by eckter** [comment] 2024-08-22 12:20
(actually I'm changing to major, it's not generally a big deal but it can be severely misleading in the wrong circumstances)

**Comment by bloussou** [comment] 2024-08-29 12:48
and they are not stick to the train
![image](https://github.com/user-attachments/assets/39fc76fb-ea7e-4f75-9f75-04ffb9a39dc2)
![image](https://github.com/user-attachments/assets/03bf2c72-761b-45a3-b8d4-c9e21548a830)

**Comment by anisometropie** [comment] 2024-09-25 12:11
I think this is fixed by https://github.com/OpenRailAssociation/osrd/pull/8954

**Comment by axrolld** [comment] 2024-09-27 07:42
Couldn't reproduce, i'm closing this, feel free to re-open if needed.

**Closed as completed by axrolld** 2024-09-27 07:42 UTC
Labels: kind:bug, area:front, severity:major, component:space-time-chart
