### ISSUE TITLE
Improve stdcm CI search performances

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#9370] opened 2024-10-17 13:27 UTC
### Who would benefit from this feature?

End users

### What is this feature about?

Searching for an operationnal point in STDCM can be rather slow and unpleasant depending on the network speed.

It would be very nice to load the results faster.

![Image](https://github.com/user-attachments/assets/592e04fa-18ac-40bf-b610-477f00bc055b)

### Database ?

![Image](https://github.com/user-attachments/assets/c9b8a160-9412-4ba3-a1db-bcda5df55cf4)

Maybe we should create some materialized views with proper indexes to improve searches.

### Why is this feature valuable?

This feature matters because this input is types by the user, which is a pretty quick action. Typing a letter takes a few ms so for this kind of component (the combo box), the speed of the response is a very important criteria.

**Comment by flomonster** [comment] 2024-12-20 16:18
Duplicate of: https://github.com/OpenRailAssociation/osrd/issues/10138

**Closed as duplicate by flomonster** 2024-12-20 16:18 UTC
Labels: kind:enhancement, module:stdcm
