### ISSUE TITLE
Modifying a train itinerary happens to delete it

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#4417] opened 2023-06-22 12:48 UTC
### What happened?

In my scenario, i wanted to edit one of my trains itinerary, but instead it got deleted.
The train list goes from 18 to 17 trains, without any warnings or anything, and i can't find my train back.

Video : https://github.com/osrd-project/osrd/assets/86296016/d518bba7-8334-4b44-ae68-fa3990b73735

I tried to chage the rolling stock and it works properly. I couldn't reproduce this bug on other train modification.

### What did you expect to happen?

The train should be edited and not deleted.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the scenario that's on the video
2. Select one of the middle_to_east trains
3. Modify it the same way it's done in the video
4. Watch it disappear
5. Cry

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 114.0.5735.134
- **OS**: Windows 10 build 19045.2965
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

Editoast f7e54dce Core f7e54dce API 511d09c1 Front f7e54dce

**Comment by flomonster** [comment] 2023-06-25 22:45
Duplicate of https://github.com/osrd-project/osrd/issues/3185

**Closed as not planned by flomonster** 2023-06-25 22:45 UTC
Labels: kind:bug, area:api (deprecated), area:editoast, module:operational-studies, severity:major
