### ISSUE TITLE
Deleted scenario still visible without refresh

### ISSUE THREAD

**Issue by flomonster** [OpenRailAssociation/osrd#8843] opened 2024-09-12 12:45 UTC
### What happened?

When a scenario is deleted, it still visible in the study page.
Once the page refreshed it disappears.

### What did you expect to happen?

We should not see deleted scenario

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Project / Study / Scenario
2. Open the created scenario
3. Delete the scenario (using the :pencil2:  button)
4. See the scenario is listed :bug: 
5. Refresh the page, the scenario is gone

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

bc8b91361c4784b9e6536bb70d1d8f113fc8f60e

**Comment by RomainValls** [comment] 2024-09-30 11:57
Can't reproduce the bug, can we close it?

**Comment by flomonster** [comment] 2024-09-30 12:00
No, I reproduced the bug on version `a5e9ca2`. Which version did you use?

**Comment by clarani** [comment] 2024-10-03 15:57
Can't reproduce anymore :white_check_mark:

**Closed as completed by clarani** 2024-10-03 15:57 UTC
Labels: kind:bug, good first issue, area:front, severity:minor
