### ISSUE TITLE
400 when trying to stick together two track sections in infra editor

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5567] opened 2023-11-02 14:02 UTC
### What happened?

I tried to fix holes in the infrastructure, bu i got this error :

https://github.com/osrd-project/osrd/assets/86296016/1c7f8acb-03c6-41c6-b4b6-bb69fdf804cd

```json
{"status":400,"data":{"status":400,"type":"editoast:operation:InvalidPatch","context":{},"message":"A Json Patch error occurred: 'Operation '/1' failed at path '/sch/coordinates/115/1': path is invalid'"}}
```

### What did you expect to happen?

I was expecting this operation to work as it does work on other parts of the infra.

### How can we reproduce it (as minimally and precisely as possible)?

1. Reproduce the video. I was near Sète train station.

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging

### OSRD version (top right corner `Account` button > `Informations`)

aa9ff62c

**Comment by sim51** [comment] 2023-11-16 14:51
duplicate of #5659

**Closed as completed by sim51** 2023-11-16 14:51 UTC
Labels: kind:bug, area:front, severity:critical, module:infra-editor
