### ISSUE TITLE
front: regression: time doesn't realtime update on train move on GET

### ISSUE THREAD

**Issue by nicolaswurtz** [OpenRailAssociation/osrd#6091] opened 2023-12-11 09:38 UTC
When moving a train with drag&drop on GET, time on timetable and on top infobar should update realtime.

![Image](https://github.com/osrd-project/osrd/assets/6003856/93ac8130-15cb-4d27-acc6-63f1cd923669)

**Comment by SharglutDev** [comment] 2023-12-12 08:06
Can't reproduce it, timetable is well updated for me (tested on dev with 1 or 5 trains in timetable)

**Comment by nicolaswurtz** [comment] 2024-01-23 14:33
@SharglutDev I'm sorry, I must have misspoken. By real time, I meant before the mouse click was released: basically, you move and the times are constantly updated.

Adding `postponed` for now: will be completely rewritten with the new GET and associated `chartmanager`.

**Comment by axrolld** [comment] 2024-10-03 15:59
I'm closing this as the GET has changed now. We will make sure this is done when implementing the drag & drop on the GET.

**Closed as completed by axrolld** 2024-10-03 15:59 UTC
Labels: kind:bug, area:front, severity:minor, postponed
