### ISSUE TITLE
front: missing translations

### ISSUE THREAD

**Issue by celine-sncf** [OpenRailAssociation/osrd#4363] opened 2023-06-14 14:51 UTC
### What happened?

When switching to english, some text is untranslated even though Transifex shows 100% completion of the translation : 
![image](https://github.com/osrd-project/osrd/assets/115472753/91abf578-5a4f-4d24-b3ae-1f1efe8dd9be)

Rolling stock categories:
![image](https://github.com/osrd-project/osrd/assets/115472753/920ae775-3cf4-44c9-be81-d9a91d3dcdc6)

### How can we reproduce it (as minimally and precisely as possible)?

1. switch the app in english

### What operating system, browser and environment are you using?

- **Browser**: Firefox v102.11esr
- **OS**: windows10
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

d4d87379

**Comment by nicolaswurtz** [comment] 2024-01-23 13:34
Thx for this issue! The problem is that the family names of rolling stocks are linked to origin country/company, so we can't change them — that comes from database — and I think we don't want to change them; it's part of their (our) nomenclature. I think it should stay as this. I close the issue regarding of this diagnostic.

**Closed as completed by nicolaswurtz** 2024-01-23 13:34 UTC
Labels: kind:bug, area:front, severity:minor
