### ISSUE TITLE
Define an API to access signalization updates from the front-end

### ISSUE THREAD

**Issue by eckter** [OpenRailAssociation/osrd#494] opened 2022-01-24 13:47 UTC
- [ ] Add signal aspect updates to the SimulationEndpoint response
- [ ] Store them in the api DB
- [ ] Add or update endpoints to make it accessible

**Comment by flomonster** [comment] 2022-01-24 14:39
Duplicate of #492

**Closed as completed by flomonster** 2022-01-24 14:39 UTC
Labels: area:core, area:api (deprecated), component:signaling
