### ISSUE TITLE
Big infrastructures are not deleted

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#7499] opened 2024-05-23 13:35 UTC
### What happened?

When you delete a big infrastructure, a message says that the infrastracture is deleted but it is still in the list and you can choose it in the map and in the editor 

### What did you expect to happen?

it should disappear

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the map and push the button to select infrastructures
2. Go to infrastructure edition
3. Duplicate a big infrastructure (like the France)
4. Try to delete it

### What operating system, browser and environment are you using?

- **Browser**: Firefox v109
- **OS**: Windows
- **Env**: Staging 

### OSRD version (top right corner `Account` button > `Informations`)

staging 3f7ff32

**Comment by flomonster** [comment] 2024-06-18 07:58
Duplicate of #6064

**Closed as completed** 2024-06-25 10:44 UTC
Labels: kind:bug, severity:minor, area:editoast
