### ISSUE TITLE
Percentage selector is hiding field in MARECO

### ISSUE THREAD

**Issue by loic-hamelin** [OpenRailAssociation/osrd#3525] opened 2023-03-14 07:42 UTC
### What happened?

When you select percentage, the size of the name of the field is too big and hide the field it self.
It happens when the app is not in full screen

### What did you expect to happen?

Not hiding the field ! 

### How can we reproduce it (as minimally and precisely as possible)?

Set the browser half size of the screen in width
Create a train
Select percentage in margins 
See the field hidden by the nam

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: IOS
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

8705e141

**Comment by Castavo** [comment] 2023-03-14 07:45
It's a duplicate of #3448

**Closed as completed by Castavo** 2023-03-14 07:45 UTC
Labels: kind:bug, area:front
