### ISSUE TITLE
A train is conflicting with itself

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#9298] opened 2024-10-10 13:59 UTC
### What happened?

When I create a train Paris - Rennes, he is conflicting with itself
it should be impossible.

this is the schedule I use : [train_schedules_bug_conflits.json](https://github.com/user-attachments/files/17329235/train_schedules_bug_conflits.json)

I was on infra 94 on recette env

### What did you expect to happen?

It should have 0 conflict

### How can we reproduce it (as minimally and precisely as possible)?

1. create a scenario with infra france 94
2. Import the train schedule I join in this issue

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox, Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

96c960e

**Comment by Castavo** [comment] 2024-10-24 12:44
Also encountered it on 7451939, happened when editing a train

**Comment by bougue-pe** [comment] 2024-11-05 17:28
Probably the same bug as the one detected in https://github.com/OpenRailAssociation/osrd/issues/9389 (to be confirmed)

**Comment by eckter** [comment] 2024-11-06 08:46
Confirmed, closing, duplicate of https://github.com/OpenRailAssociation/osrd/issues/9389

**Closed as not planned by eckter** 2024-11-06 08:46 UTC
Labels: kind:bug, area:core, severity:critical, component:conflict-detection
