### ISSUE TITLE
map Performance, moving the train in simulation is not smooth

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#3060] opened 2023-02-01 08:41 UTC
- Proposal with Deck.GL layer
- memoization
- do not recompute the mediator everytime

**Comment by bloussou** [comment] 2023-02-01 10:19
What do you mean by map performances ? Is it time to display the infra, signals, ... ?

**Comment by anisometropie** [comment] 2023-02-17 17:44
@bloussou More like when we hover over the map, to move the train, or over the graphes, it’s not always smooth

**Comment by axrolld** [comment] 2024-02-09 15:58
Duplicate of #2572

**Closed as completed by axrolld** 2024-02-09 15:58 UTC
Labels: area:front
