### ISSUE TITLE
output table enhancement

### ISSUE THREAD

**Issue by anisometropie** [OpenRailAssociation/osrd#8182] opened 2024-07-25 10:47 UTC
- we should have a threshold where we snap the calculated arrival time to the requested arrival time 

_Originally posted by @flomonster in https://github.com/OpenRailAssociation/osrd/pull/7855#pullrequestreview-2196919489_

**Comment by flomonster** [comment] 2024-07-26 10:22
Duplicate of https://github.com/OpenRailAssociation/osrd/issues/8185

**Closed as completed** 2024-07-26 14:01 UTC
Labels: kind:enhancement, area:front
