### ISSUE TITLE
Time selection shows unwated space between 0 and 1

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#4416] opened 2023-06-22 12:38 UTC
### What happened?

Unwanted space between 0 and 1 here, in STDCM :
![image](https://github.com/osrd-project/osrd/assets/86296016/a342bd3d-5a42-428a-900b-4499734ba2da)

This happens in the minutes and the seconds columns.

This bug is also visible in the train creation window in operationnal studies.

### What did you expect to happen?

The should be no space between those numbers.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to STDCM
2. Try to set departure time by clicking on the clock
3. Scroll the minutes or the seconds to display the space between 0 and 1

### What operating system, browser and environment are you using?

- **Browser**: Chrome Version 114.0.5735.134
- **OS**: Windows 10 build 19045.2965
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

Editoast f7e54dce Core f7e54dce API 511d09c1 Front f7e54dce

**Comment by RomainValls** [comment] 2023-11-30 09:49
Bug seems to be fixed now ?

**Comment by nicolaswurtz** [comment] 2024-01-23 13:31
Hey! Thx for reporting, but the call to the datetime picker is a native one: it's your browser that displays the little time selection popup, so we don't have any control over it.

In a next future, our glorious UX master will probably design a dedicated datetime picker, to unify all browser behaviour. I close the issue because it's, by design, irrelevant.

**Closed as completed by nicolaswurtz** 2024-01-23 13:31 UTC
Labels: kind:bug, good first issue, area:front, severity:minor, module:stdcm, module:operational-studies
