### ISSUE TITLE
Sort by name/latest for Scénario is in descending order

### ISSUE THREAD

**Issue by Morgane-SJK** [OpenRailAssociation/osrd#7624] opened 2024-06-05 13:37 UTC
### What happened?

When i want to sort my Scenarios, they are ordered in descending order:

- sort by name : A1 is at the end
![image](https://github.com/OpenRailAssociation/osrd/assets/95025398/f5cf2599-f74f-4b11-8643-c7d65a562666)

- sort by latest : the latest Scénario is at the end
![image](https://github.com/OpenRailAssociation/osrd/assets/95025398/928654fd-f6b8-4dde-9cab-5f0e00394137)

### What did you expect to happen?

The Scenarios should be ordered in ascending order, as it is the case when we sort Projects or Studies

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to Operational Studies
2. Select a Project
3. Select a Study
4. Create at least 2 scénarios : (named A and Z for example)

### What operating system, browser and environment are you using?

- **Browser**: Chrome version 124.0.6367.202
- **OS**: Windows
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

dev ffb0014

**Comment by theocrsb** [comment] 2024-08-08 09:16
Can't reproduce

**Comment by Caracol3** [comment] 2024-08-21 09:16
I think we can close this issue. The last time I checked, the scenarios were well-ordered.

**Comment by clarani** [comment] 2024-09-13 12:16
Can't reproduce either, I close it

**Closed as completed by clarani** 2024-09-13 12:16 UTC
Labels: kind:bug, area:front, severity:minor, module:operational-studies
