### ISSUE TITLE
deleting invalid object still leaves the  object on the map

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#5951] opened 2023-12-01 08:22 UTC
### What happened?

When deleting an invalid object, the deletion is successful but it still leaves the object on the map for a while

![image](https://github.com/osrd-project/osrd/assets/113104137/ef0fb4b2-0c52-4729-8137-7aee26597f9d)

### What did you expect to happen?

The object should be definitively removed from the map after its deletion

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to infra editor
2. Create a track section and then create a detector on it
3. Delete the track section which will result for an issue with this detector
4. Delete the detector 
5. It should still remain on the map like the screenshot above

### What operating system, browser and environment are you using?

- **Browser**: Firefox v118
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 7796e6d

**Comment by flomonster** [comment] 2023-12-01 08:37
Duplicate of https://github.com/osrd-project/osrd/issues/5931

**Closed as not planned by flomonster** 2023-12-01 08:37 UTC
Labels: kind:bug, area:front, severity:minor, module:infra-editor
