### ISSUE TITLE
Deleted infrastructure is still in the list

### ISSUE THREAD

**Issue by bgiuliana** [OpenRailAssociation/osrd#6122] opened 2023-12-14 14:50 UTC
### What happened?
After waiting for the end of deleting procedure, the infrastructure is still in the list till you exit from the modal.

### How can we reproduce it (as minimally and precisely as possible)?
1. Go to the editor
2. Duplicate the infrastructure
3. Delete the infrastructure copy
4. The deleted infra is still in the list 

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: staging dgex sol

### OSRD version (top right corner `Account` button > `Informations`)

ff14422

**Comment by bloussou** [comment] 2024-01-11 14:24
I'm closing this as I cannot reproduce it. Feel free to reopen if you still have the issue

**Closed as completed by bloussou** 2024-01-11 14:24 UTC
Labels: kind:bug, area:front, severity:minor
