### ISSUE TITLE
Numeric field should have place holders and not default value

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#5221] opened 2023-10-05 12:50 UTC
For instance in these fields:

![Image](https://github.com/osrd-project/osrd/assets/32448554/0333ffe4-a661-45cd-a3a2-76aecef9eee9)

The `0` is a default value not a placeholder, so it is immpossible to remove the `0` and if you want a `3%` margin you will have either `03` or `30` and then remove the 0.

List of the concerned inputs
- [x] #5548 
- [x] #5549
- [x] #5550 

Version: cb78a63b

**Comment by clarani** [comment] 2023-10-06 14:27
The problem is that the min value of this input should be 1 (discussed with Nicolas and Mathieu)

**Comment by bloussou** [comment] 2023-10-26 13:37
Not related to the value but to the fact that there is a 0 you cannot remove...

**Comment by bloussou** [comment] 2023-10-26 13:37
Same issue spotted here : [#5477](https://github.com/osrd-project/osrd/issues/5477)

**Comment by clarani** [comment] 2023-11-16 09:22
I close this ticket since the 3 PRs have been merged 🎉

**Closed as completed by clarani** 2023-11-16 09:22 UTC
Labels: kind:bug, area:front, severity:minor
