### ISSUE TITLE
Editor : Created objects disappear, Deleted objects are still visible, and Zoom brings strange behaviors

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#3323] opened 2023-02-23 11:20 UTC
### What happened?

When we create an object, sometimes, it disappears. 
This applies to buffer stop, detector, switch, tracks, ...

When we try to delete an object, it is still visible on the map.
This applies to buffer stop, detector, switch, tracks, ...

All of this behaviours could depend on the zooming level.
(at a certain zooming level, all the infra disappear)

https://user-images.githubusercontent.com/27173221/220954769-53a125c0-d2b0-46bd-a920-b33c906513fd.mp4

### What did you expect to happen?

The object should be visible when it is created.
The object should disappear when it is deleted.

We could see all our infra at any zooming level.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go on the editor
2. Create objects
2. Delete objects
2. Zoom/Dezoom

### What operating system, browser and environment are you using?

- **Browser**: Chrome v110
- **OS**: Windows 10
- **Env**: Dgex dev

### OSRD version (top right corner `Account` button > `Informations`)

22a23a45

**Comment by jacomyal** [comment] 2023-03-14 11:23
@Tguisnet I can't reproduce the issue locally, now that PRs #3485 and #3492 have been merged. Do you confirm it does not occur anymore?

**Closed as completed** 2023-03-31 09:26 UTC
Labels: kind:bug, severity:critical, module:infra-editor
