### ISSUE TITLE
Infra loading status is blocked to `1/8` in STDCM page

### ISSUE THREAD

**Issue by bloussou** [OpenRailAssociation/osrd#6387] opened 2024-01-18 13:41 UTC
This issue is critical because you cannot click on apply if this is not fully loaded:

![Image](https://github.com/osrd-project/osrd/assets/32448554/0e1e7db2-2edf-4412-8530-e6c1b22900a0)

In another tab I can see that the infra is loaded:

![Image](https://github.com/osrd-project/osrd/assets/32448554/25f334c5-7997-4808-8149-2361d1588f50)

To reproduce:
1. Create a stdcm train in a timetable with an infra not loaded
2. it will be blocked to `1/8`

Version: `staging 39c05f1`

**Comment by bloussou** [comment] 2024-01-18 13:51
@flomonster failed to reproduce so decreasing criticality to minor

**Comment by nicolaswurtz** [comment] 2024-01-23 14:57
Thx for reporting, albeit I'm not able to reproduce too (apply button is unavailable, as it should).
I close the issue for now. If the bug appears again, reopen the issue and add more precision on how to reproduce, thx!

**Closed as completed by nicolaswurtz** 2024-01-23 14:57 UTC
Labels: kind:bug, area:front, severity:minor, module:stdcm
