### ISSUE TITLE
Buildings are hiding track layers

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#5571] opened 2023-11-02 14:34 UTC
### What happened?

The buildings in some train station are hiding the tracks, as it's the case here in Bordeaux train station:
![image](https://github.com/osrd-project/osrd/assets/86296016/1b72c1b2-985f-47e4-8ed1-c64fc490134d)

### What did you expect to happen?

I know the buildings are physically above the tracks but the track layer should never be hidden in my opinion. Otherwise we won't be able to work in tunnels...

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the map
2. Bordeaux-Saint-Jean train station

### What operating system, browser and environment are you using?

- **Browser**: Chrome
- **OS**: W11
- **Env**: dev

### OSRD version (top right corner `Account` button > `Informations`)

c2b9acd3

**Comment by flomonster** [comment] 2023-11-13 09:04
Duplicate of https://github.com/osrd-project/osrd/issues/4872

**Closed as not planned by flomonster** 2023-11-13 09:04 UTC
Labels: kind:bug, area:front, severity:minor, module:carto
