### ISSUE TITLE
stdcm: wrong font in selector

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#9709] opened 2024-11-14 10:09 UTC
### What happened?

![Image](https://github.com/user-attachments/assets/6b7b3d78-efa9-470a-accc-28afcee9f513)

![Image](https://github.com/user-attachments/assets/49cc8a93-108e-4a84-96b3-70ca0d8e216a)

![Image](https://github.com/user-attachments/assets/13847edd-8637-49ad-aaa5-274a81fa21c0)

![Image](https://github.com/user-attachments/assets/063946db-ee35-4e07-a2f0-83bbf91f38da)

### How can we reproduce it (as minimally and precisely as possible)?

1. open LMR

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

staging cd4cdfb

**Comment by bougue-pe** [comment] 2024-11-14 17:05
Duplicate of https://github.com/OpenRailAssociation/osrd/issues/9173

**Closed as not planned by bougue-pe** 2024-11-14 17:05 UTC
Labels: kind:bug, area:front, severity:minor, module:stdcm
