### ISSUE TITLE
stdcm: `conflicts` status even with an empty conflit list

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#9531] opened 2024-10-31 13:56 UTC
### What happened?

Tried to find a last minute train path in a scenario with no train, and got this:
![Image](https://github.com/user-attachments/assets/dc749ebd-4c9e-40f2-b53c-4d387c31db7d)
![Image](https://github.com/user-attachments/assets/d0dde369-21f5-40ad-9be6-715411d4fcda)

### What did you expect to happen?

It should display the result if the request was successful.

### How can we reproduce it (as minimally and precisely as possible)?

These inputs
![Image](https://github.com/user-attachments/assets/0af69929-1036-4db4-a17e-c986e7ae5cc1)

```json
{"comfort":"STANDARD","margin":"4.5min/100km","rolling_stock_id":54,"towed_rolling_stock_id":6,"total_mass":100000,"max_speed":27.77777777777778,"total_length":200,"steps":[{"duration":0,"location":{"uic":87743005,"secondary_code":"BV"},"timing_data":{"arrival_time":"2024-09-26T07:00:00+02:00","arrival_time_tolerance_before":3600000,"arrival_time_tolerance_after":2100000}},{"duration":0,"location":{"uic":87743716,"secondary_code":"BV"}}],"time_gap_after":35000,"time_gap_before":35000,"work_schedule_group_id":20,"loading_gauge_type":"GA"}
```

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

a9261bc

**Comment by axrolld** [comment] 2024-10-31 14:03
My bad, this is actually dupliacte with https://github.com/OpenRailAssociation/osrd/issues/9508

**Comment by axrolld** [comment] 2024-10-31 14:26
Actually it's a different bug, i'm re-opening this.

**Comment by eckter** [comment] 2024-11-06 08:29
What happened in this case was that the train didn't have enough traction to reach the destination. It shouldn't normally happen (it would fail at preprocessing) but because of https://github.com/OpenRailAssociation/osrd/issues/9544 it may sometimes be possible. 

There's some weird behavior around where the train maybe should actually have enough traction. But I couldn't reproduce that part since last week.

I'm closing this, we can reopen if we see new issues with a lack of traction.

**Closed as completed by eckter** 2024-11-06 08:29 UTC
Labels: kind:bug, area:core, module:stdcm, severity:critical
