### ISSUE TITLE
Impossible to add a new speed limit with a psl

### ISSUE THREAD

**Issue by SharglutDev** [OpenRailAssociation/osrd#5794] opened 2023-11-22 11:18 UTC
### What happened?

In the infra editor, when adding a new speed limit with a basic psl (only Z panel), we get an error : 

![image](https://github.com/osrd-project/osrd/assets/113104137/5981775a-7f3a-43d6-8fdf-6f86db9a7a6e)

To fix this one, we can set `value: ''` instead of `value: null` in components.tsx from rangeEdition. 
But the value shouldn't be required for Z and R panels.

If we fix this issue, we get a new one :

![image](https://github.com/osrd-project/osrd/assets/113104137/900e36d3-5f6a-4896-8a3b-65d353c6e8c7)

The cause comes from `Sign` struct in mod.rs file which requires a kp field that we do not provide in the front for now.

### What did you expect to happen?

Adding a new speed limit witrh a psl should work

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to infra editor
2. Add a new speed limit with a psl and save

### What operating system, browser and environment are you using?

- **Browser**: Firefox v118
- **OS**: Ubuntu
- **Env**: Dev

### OSRD version (top right corner `Account` button > `Informations`)

dev 51df1a8

**Comment by jacomyal** [comment] 2023-11-22 13:50
Closing because duplicate of #5792.

**Closed as completed by jacomyal** 2023-11-22 13:50 UTC
Labels: kind:bug, area:editoast, severity:critical, module:infra-editor
