### ISSUE TITLE
Core: Arrival Time whithout Time Stop at the end of a schedule fail

### ISSUE THREAD

**Issue by Tguisnet** [OpenRailAssociation/osrd#8335] opened 2024-08-05 14:43 UTC
### What happened?

When we have an Arrival Time whithout a Time Stop at the end of a schedule, core seems to crash.

![Image](https://github.com/user-attachments/assets/cca0ab54-da57-4b87-af09-dd9166cbe1b6)

### What did you expect to happen?

We should be able to handle an Arrival Time whithout a Time Stop

### How can we reproduce it (as minimally and precisely as possible)?

Train schedule example: [train_schedules.json](https://github.com/user-attachments/files/17247032/train_schedules.json)

**OR**

1. Create a new train schedule
1. Put an Arrival Time whithout a Time Stop at the end of the schedule
1. The train scedule is invalid with a "Simulation Failed"

### On which environments the bug occurs?

Local

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

0f97f32f7509cc9722a1a33bec7462ee22009e82

**Comment by eckter** [comment] 2024-11-14 09:07
That's not *really* a bug.

Allowances keep start and end speeds identical (by design). If a train doesn't stop at its end, it may just accelerate over its whole path. In that case we can't do anything other than accelerate to keep the same end speed. That's generally the cause of the issue.

If we want to prevent this from happening, we'd need to change the allowance behavior and semantics in significant ways. It wouldn't be a bugfix but a complete rework.

I'm closing this as the behavior fits the specs, but we can eventually open a rework ticket if we need to.

**Closed as not planned by eckter** 2024-11-14 09:07 UTC
Labels: kind:bug, area:core, severity:major
