### ISSUE TITLE
Weird "simulation failed" in operationnal studies

### ISSUE THREAD

**Issue by maelysLeratRosso** [OpenRailAssociation/osrd#9634] opened 2024-11-07 13:36 UTC
### What happened?

When we create these trains : [train_schedules (11).json](https://github.com/user-attachments/files/17662221/train_schedules.11.json) (bug with a RS 84500 ; not with BB 64700)
they are invalid with "simulation failed" message. If we remove the times at the waypoints, the train becomes valid. This is strange because if a train cannot respect its timed points, it should not be valid.

I get this error
![Image](https://github.com/user-attachments/assets/92e9d34d-56bf-4a3b-9ee7-9330f5e09752)

### What did you expect to happen?

I expected the train to be valid

### How can we reproduce it (as minimally and precisely as possible)?

Import the previous file

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

e9f3b96

**Comment by eckter** [comment] 2024-11-07 13:59
Caused by https://github.com/OpenRailAssociation/osrd/issues/9037

**Comment by eckter** [comment] 2024-11-14 09:00
Closing, duplicate of https://github.com/OpenRailAssociation/osrd/issues/9037

**Closed as not planned by eckter** 2024-11-14 09:00 UTC
Labels: kind:bug, area:core, module:operational-studies, severity:major, postponed
