### ISSUE TITLE
[REMINDER] Adapt logic to undo/redo requirements for train Suppression

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#707] opened 2022-03-23 17:40 UTC

**Comment by alexandredamiron** [comment] 2022-04-06 13:59
Redo is too experimental without delete rollback

**Comment by multun** [comment] 2023-09-20 19:54
Duplicate of #708
Please do not create duplicate issues.

**Closed as not planned by multun** 2023-09-20 19:54 UTC
Labels: area:front
