### ISSUE TITLE
Position of train on the map must be precise: Provide a test case

### ISSUE THREAD

**Issue by alexandredamiron** [OpenRailAssociation/osrd#1363] opened 2022-07-04 08:25 UTC
The current representation of train position on the map seems to be unaacurate: at certain stops times, train is represented before or after the concerned PR.

**Comment by alexandredamiron** [comment] 2022-07-04 08:36
Provide to back engineering a test cas with clear unaccurate position and screenshot

- [ ] describe the parameters of simulation
- [ ] provide screenshots

**Comment by alexandredamiron** [comment] 2022-07-04 08:50
relate to #1365

**Comment by axrolld** [comment] 2022-07-18 16:45
Closing this issue because it was in the Done piepline of the board.

**Closed as completed by axrolld** 2022-07-18 16:45 UTC

**Comment by multun** [comment] 2022-07-19 09:44
I can confirm it's been done
