### ISSUE TITLE
STDCM fail

### ISSUE THREAD

**Issue by axrolld** [OpenRailAssociation/osrd#8614] opened 2024-08-29 13:32 UTC
### What happened?

I tried to run a STDCM with these inputs:

![image](https://github.com/user-attachments/assets/60f6eb53-93a0-48d8-85fe-ff114b6c241f)

And got a fail.

Logs:

> [13:27:17,795] [INFO]         [STDCMHeuristic] Start building STDCM heuristic...                                                                   │
│ [13:27:18,814] [INFO]         [STDCMHeuristic] STDCM heuristic built, best theoretical travel time = 12948 seconds                                 │
│ [13:27:19,162] [INFO]                  [STDCM] node sample for progress 1/10: time=2387s, since departure=1563s, best remaining time=11637s, loc={ │
│ [13:27:19,620] [INFO]                  [STDCM] node sample for progress 2/10: time=4003s, since departure=3179s, best remaining time=10330s, loc={ │
│ [13:27:20,711] [INFO]                  [STDCM] node sample for progress 3/10: time=7467s, since departure=4759s, best remaining time=9023s, loc={l │
│ [13:27:22,094] [INFO]                  [STDCM] node sample for progress 4/10: time=11321s, since departure=6393s, best remaining time=7732s, loc={ │
│ [13:27:22,225] [INFO]                  [STDCM] node sample for progress 5/10: time=9540s, since departure=8116s, best remaining time=6399s, loc={l │
│ [13:27:22,290] [INFO]                  [STDCM] node sample for progress 6/10: time=11152s, since departure=9727s, best remaining time=5136s, loc={ │
│ [13:27:22,425] [INFO]                  [STDCM] node sample for progress 7/10: time=14708s, since departure=11993s, best remaining time=3815s, loc= │
│ [13:27:22,492] [INFO]                  [STDCM] node sample for progress 8/10: time=16307s, since departure=13591s, best remaining time=2573s, loc= │
│ [13:27:22,539] [INFO]                  [STDCM] node sample for progress 9/10: time=18022s, since departure=15303s, best remaining time=1242s, loc= │
│ [13:27:22,696] [INFO]                  [STDCM] node sample for progress 10/10: time=19616s, since departure=16897s, best remaining time=0s, loc={l │
│ [13:27:22,697] [INFO]                  [STDCM] Path found, start postprocessing                                                                    │
│ [13:27:22,943] [INFO]                  [STDCM] Conflict when running final stdcm simulation at offset 45744.797m, adding a fixed time point        │
│ [13:27:23,147] [INFO]                  [STDCM] Conflict when running final stdcm simulation at offset 66890.977m, adding a fixed time point        │
│ [13:27:23,342] [INFO]                  [STDCM] Conflict when running final stdcm simulation at offset 241958.328m, adding a fixed time point       │
│ [fr.sncf](http://fr.sncf/).osrd.reporting.exceptions.OSRDError: Failed to converge when computing allowances because of a discontinuity in the search space           │
│     at [fr.sncf](http://fr.sncf/).osrd.envelope_sim.allowances.AbstractAllowanceWithRanges.makeError([AbstractAllowanceWithRanges.java:113](http://abstractallowancewithranges.java:113/))                            │
│     at [fr.sncf](http://fr.sncf/).osrd.envelope_sim.allowances.AbstractAllowanceWithRanges.computeAllowanceSection([AbstractAllowanceWithRanges.java:374](http://abstractallowancewithranges.java:374/))              │
│     at [fr.sncf](http://fr.sncf/).osrd.envelope_sim.allowances.AbstractAllowanceWithRanges.computeAllowanceRange([AbstractAllowanceWithRanges.java:308](http://abstractallowancewithranges.java:308/))                │
│     at [fr.sncf](http://fr.sncf/).osrd.envelope_sim.allowances.AbstractAllowanceWithRanges.computeAllowanceRegion([AbstractAllowanceWithRanges.java:233](http://abstractallowancewithranges.java:233/))               │
│     at [fr.sncf](http://fr.sncf/).osrd.envelope_sim.allowances.AbstractAllowanceWithRanges.apply([AbstractAllowanceWithRanges.java:133](http://abstractallowancewithranges.java:133/))                                │
│     at [fr.sncf](http://fr.sncf/).osrd.stdcm.graph.PostProcessingSimulationKt.runSimulationWithFixedPoints(PostProcessingSimulation.kt:315)                           │
│     at [fr.sncf](http://fr.sncf/).osrd.stdcm.graph.PostProcessingSimulationKt.buildFinalEnvelope(PostProcessingSimulation.kt:89)                                      │
│     at [fr.sncf](http://fr.sncf/).osrd.stdcm.graph.PostProcessingSimulationKt.buildFinalEnvelope$default(PostProcessingSimulation.kt:50)                              │
│     at [fr.sncf](http://fr.sncf/).osrd.stdcm.graph.STDCMPostProcessing.makeResult(STDCMPostProcessing.kt:75)                                                          │
│     at [fr.sncf](http://fr.sncf/).osrd.stdcm.graph.STDCMPathfinding.findPath(STDCMPathfinding.kt:128)                                                                 │
│     at [fr.sncf](http://fr.sncf/).osrd.stdcm.graph.STDCMPathfindingKt.findPath(STDCMPathfinding.kt:73)                                                                │
│     at [fr.sncf](http://fr.sncf/).osrd.api.api_v2.stdcm.STDCMEndpointV2.act(STDCMEndpointV2.kt:94)                                                                    │
│     at [fr.sncf.osrd.cli.WorkerCommand.run](http://fr.sncf.osrd.cli.workercommand.run/)$lambda$2(WorkerCommand.kt:182)                                                                           │
│     at com.rabbitmq.client.impl.recovery.AutorecoveringChannel$4.handleDelivery([AutorecoveringChannel.java:642](http://autorecoveringchannel.java:642/))                                    │
│     at datadog.trace.instrumentation.rabbitmq.amqp.TracedDelegatingConsumer.handleDelivery([TracedDelegatingConsumer.java:79](http://traceddelegatingconsumer.java:79/))                       │
│     at com.rabbitmq.client.impl.ConsumerDispatcher$[5.run](http://5.run/)([ConsumerDispatcher.java:149](http://consumerdispatcher.java:149/))                                                              │
│     at com.rabbitmq.client.impl.ConsumerWorkService$[WorkPoolRunnable.run](http://workpoolrunnable.run/)([ConsumerWorkService.java:111](http://consumerworkservice.java:111/))                                             │
│     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker([ThreadPoolExecutor.java:1144](http://threadpoolexecutor.java:1144/))                                                   │
│     at java.base/java.util.concurrent.ThreadPoolExecutor$[Worker.run](http://worker.run/)([ThreadPoolExecutor.java:642](http://threadpoolexecutor.java:642/))                                                   │
│     at java.base/[java.lang.Thread.run](http://java.lang.thread.run/)([Thread.java:1583](http://thread.java:1583/))

And the schedule:
[train_schedules(8).json](https://github.com/user-attachments/files/16799858/train_schedules.8.json)

### How can we reproduce it (as minimally and precisely as possible)?

Everything is in the description

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

80973c5

**Comment by eckter** [comment] 2024-09-03 13:33
I couldn't reproduce (I had issues to create the same env).

It's related to https://github.com/OpenRailAssociation/osrd/issues/8554 and I assume it's just a matter of finding the right tolerance. I've opened a PR to log more details if it happens again: https://github.com/OpenRailAssociation/osrd/pull/8720

I'll stop actively looking into this for now, I'll wait to see if it happens again. I'll then use the extra logged data to figure this out.

I'll bump the severity down, it seems actually quite uncommon (since the previous PR on this matter).

**Comment by eckter** [comment] 2024-10-17 12:36
Likely fixed by https://github.com/OpenRailAssociation/osrd/pull/9137

**Closed as completed by eckter** 2024-10-17 12:36 UTC
Labels: kind:bug, area:core, module:stdcm, severity:major, postponed
